# Generated by Django 3.1.1 on 2020-09-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(choices=[('1', 'Bulawayo'), ('2', 'Harare'), ('3', 'Manicaland'), ('4', 'Mashonaland Central'), ('5', 'Mashonaland East'), ('6', 'Mashonaland West'), ('7', 'Masvingo'), ('8', 'Matebeleland North'), ('9', 'Matebeleland South'), ('10', 'Midlands')], default='1', max_length=2)),
                ('district', models.CharField(choices=[('1', 'Bulawayo'), ('2', 'Harare'), ('3', 'Manicaland'), ('4', 'Mashonaland Central'), ('5', 'Mashonaland East'), ('6', 'Mashonaland West'), ('7', 'Masvingo'), ('8', 'Matebeleland North'), ('9', 'Matebeleland South'), ('10', 'Midlands')], default='1', max_length=12)),
                ('location', models.CharField(choices=[('p', 'Peri-urban'), ('r', 'Rural'), ('u', 'Urban')], default='p', help_text='Where is your school located', max_length=1)),
                ('board', models.CharField(choices=[('b', 'Boarding'), ('d', 'Day')], default='d', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('cell_number', models.CharField(max_length=13)),
                ('specialisation', models.CharField(max_length=20)),
                ('level_taught', models.CharField(blank=True, choices=[('p', 'Primary'), ('s', 'Secondary')], default='p', help_text='Level taught at', max_length=1)),
                ('grade_taught', models.CharField(blank=True, choices=[('A', 'ECD A'), ('B', 'ECD B'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7')], default='A', help_text='Grade taught at', max_length=1)),
                ('form_taught', models.CharField(blank=True, choices=[('1', 'Form 1'), ('2', 'Form 2'), ('3', 'Form 3'), ('4', 'Form 4'), ('5', 'Form 5'), ('6', 'Form 6')], default='1', help_text='Form taught at', max_length=1)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swops.school')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
    ]
